import type { Metadata } from "next";
import "./globals.css";
import MarginWrapper from "@/common/MarginWrapper";
import Navbar from "@/common/Navbar";
import Footer from "@/common/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >
          <Navbar/>
        {/* <MarginWrapper> */}
          {children}
          {/* </MarginWrapper> */}
          <Footer/>
      </body>
    </html>
  );
}
